services:
  backend:
    build:
      context: backend
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    restart: on-failure


  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: houz
