services:
  backend:
    build:
      context: backend
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: houz
